gzip_assets: off

javascripts:
  defaults:
    - public/javascripts/jquery.js
    - public/javascripts/jquery-ui.js
    - public/javascripts/rails.js
    - public/javascripts/application.js
  editor:
    - public/javascripts/editor.js
  canvas:
    - public/javascripts/jquery.contextmenu.js
    - public/javascripts/jquery.rotate.js
    - public/javascripts/colorpicker.js
    - public/javascripts/canvas.js

stylesheets:
  all:
    - public/stylesheets/*.css
