embed_assets: on

javascripts:
  defaults:
    - public/javascripts/jquery.js
    - public/javascripts/jquery-ui.js
    - public/javascripts/rails.js
  editor:
    - public/javascripts/editor.js

stylesheets:
  all:
    - public/stylesheets/*.css

